import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Algebra 2H',
                  teacher_name='Mr. Shelton',
                  resource_name='slader.com',
                  resource_url='http://www.slader.com/subject/math/algebra-2/textbooks/'),
    course.Course(period=3,
                  name='US History',
                  teacher_name='Ms. Chin',
                  resource_name='hmhco.com',
                  resource_url='https://www.hmhco.com/search/shop/social+studies'),
    course.Course(period=4,
                  name='Chemistry',
                  teacher_name='Mr. Hockenos',
                  resource_name='hmhco.com',
                  resource_url='https://www.hmhco.com/search/shop?term=modern+chemistry'),
    course.Course(period=5,
                  name='English 3CP',
                  teacher_name='Mrs. Marder',
                  resource_name='Spark Notes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=6,
                  name='C Aid for Lang',
                  teacher_name='Mrs. Geiser',
                  resource_name='Schoolloop.com',
                  resource_url='http://ssfhs.schoolloop.com/'),
]
